In [1]:
print('Hola mundo')

Hola mundo


In [3]:
import numpy as np

array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.37393288 0.38195663]
 [0.9406124  0.81168555]]


In [11]:
vacia = np.empty((3,4))
print(vacia)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
full = np.full((3,3), 7)
print(full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [15]:
espacio1 = np.arange(0,30,5)
print(espacio1)

espacio2 = np.linspace(0,2,5)
print(espacio2)

[ 0  5 10 15 20 25]
[0.  0.5 1.  1.5 2. ]


In [17]:
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
print(identidad1.ndim)

2


In [21]:
print(identidad2.dtype)

float64


In [23]:
print(aleatorios.size)
print(aleatorios.shape)

4
(2, 2)
